# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^data/
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-case-conflict
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.12
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        files: \.(md|qmd)$
        types: [file]
        exclude: LICENSE.md
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
